language: go

go:
  - "1.10.3"

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...

after_script:
  - go get github.com/modocache/gover; gover
  - bash <(curl -s https://codecov.io/bash)