language: go

go:
  - "1.10.3"

cache:
  directories:
    - ${HOME}/ATS2

before_install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libgmp-dev
  - sudo apt-get install -y libgc-dev
  - sudo apt-get install -y libjson-c-dev
  - ./build_ats

env:
  - PATSHOME="${HOME}/ATS2"
  - PATH="${PATSHOME}/bin:${PATH}"

script:
  - pwd && go test -v -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...

after_script:
  - go get github.com/modocache/gover; gover
  - bash <(curl -s https://codecov.io/bash)
