language: go

go:
  - "1.10.3"

cache:
  directories:
    - ${HOME}/ATS2

before_install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libgmp-dev
  - sudo apt-get install -y libgc-dev
  - sudo apt-get install -y libjson-c-dev
  - git clone "git://git.code.sf.net/p/ats2-lang/code" ${HOME}/ATS2
  - (cd ${PATSHOME} && ./configure && make all)

env:
  - PATSHOME=${HOME}/ATS2

script:
  - pwd && go test -v -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...

after_script:
  - go get github.com/modocache/gover; gover
  - bash <(curl -s https://codecov.io/bash)